name: reusable 3 1

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  SHELL: /bin/bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Verify environment
      run : |
        echo "Environment variable info es ${{ vars.INFO }}"
  


