name: reusable 3 1

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: mostrar las variables
        run: |
          # pinta las variables cargadas
          echo "la API_URL es $env.API_URL"
          echo "la info es $env.INFO"
  


