name: reusable 3 1

on:
  workflow_dispatch:

env:
  SHELL: /bin/bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Verify environment
      run : |
        echo "Environment variable info es ${{ vars.INFO }}"


