name: reusable 3 1

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      info:
        required: true
        type: string
      api:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar las variables pasadas
        run: |
          echo "la API_URL es ${{ inputs.api }}"
          echo "la info es ${{ inputs.info }}"
          echo "el envionment sería ${{ inputs.environment }}"


