name: reusable 3 1

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      API_URL: ${{ vars.API_URL }}
      INFO: ${{ vars.INFO }}
      
    steps:
      - name: mostrar lvariables
        run: |
          echo "la API_URL es $API_URL"
          echo "la info es $INFO"

