name: reusable 3 1

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: pintar variables segun environment
        run: |
          echo "la API_URL es ${{ vars.API_URL }}"
          if [ "${{ inputs.environment }}" = "development" ]; then
            echo "la info de development es ${{ vars.DEVELOPMENT_INFO }}"
          elif [ "${{ inputs.environment }}" = "staging" ]; then
            echo "la info de staging es ${{ vars.STAGING_INFO }}"
          elif [ "${{ inputs.environment }}" = "production" ]; then
            echo "la info de production es ${{ vars.PRODUCTION_INFO }}"
          fi

